<a href="https://colab.research.google.com/github/sejal-oli7/python/blob/main/python%20/%20%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas Exercise 1
We need pandas to get to know about the pandas.

In [ ]:
#@ Importing necessary
import pandas as pd
import numpy as np

In [15]:
import pandas as pd

df = pd.read_csv("food.tsv", sep="\t")

print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'food.tsv'

## Pandas EXercise 2

In [16]:
#@ IMporting Library
import pandas as pd
import numpy as np

In [17]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"

df = pd.read_csv(
    url,
    sep="|",
    index_col="user_id"
)

print(df.head())

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [18]:
df.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [19]:
df.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [20]:
#@ how many numbers of data we have?
df.shape [0]

943

In [21]:
df.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [22]:
df.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [23]:
#@ only print occupation columns
df.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [24]:
df['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [25]:
#@ how many different occupations are in the datasets
df.occupation.nunique()

21

In [26]:
df.occupation.value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [ ]:
df.occupation.value_counts().count()

In [ ]:
#@ Lets describe your dataset by summarizing it
df.describe()

Only numeric columns are return , if you only describe the dataframe

In [ ]:
#@ If we need all then
df.describe(include="all")

In [27]:
df.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [28]:
#@ what is the mean age of users?
round(df.age.mean())

34

In [29]:
#@ the least occurance of age
df.age.value_counts().tail()

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64

## Pandas Exercise3

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url, sep='\t')

In [ ]:
#@ inspecting the dataset
df.head(20)

In [ ]:
#@ number of observation
df.shape[0]

In [ ]:
df.info()

In [ ]:
df.shape[1]

In [ ]:
df.columns

In [ ]:
#@ which was the most order items
#group by
i = df.groupby('item_name')
i
i= i.sum()
i = i.sort_values(['quantity'], ascending=False)
i.head(1)

In [ ]:
#@ what was the most order item in the choice description column
df.groupby('choice_description').sum().sort_values(['quantity'], ascending=False).head(1)

In [9]:
import pandas as pd
data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ],
    "date_Of_Birth": [
        "15/05/2002",
        "17/05/2002",
        "16/02/1999",
        "25/09/1998",
        "11/05/2002",
        "15/09/1997"
    ],
    "age": [12, 12, 13, 13, 14, 12],
    "height": [173, 192, 186, 167, 151, None],
    "weight": [35, 32, 33, 30, 31, None],
    "address": [
        "street1",
        "street2",
        "street3",
        "street1",
        "street2",
        None
    ]
}

df = pd.DataFrame(data)

# Group by school
grouped = df.groupby("school")

# Check the type
print(type(grouped))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [10]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "age": [12, 12, 13, 13, 14, 12]
}

df = pd.DataFrame(data)

result = df.groupby("school")["age"].agg(
    ["mean", "min", "max"]
)

print(result)

        mean  min  max
school
s001    12.5   12   13
s002    13.0   12   14
s003    13.0   13   13
s004    12.0   12   12

In [11]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ],
    "age": [12, 12, 13, 13, 14, 12]
}

df = pd.DataFrame(data)

grouped = df.groupby(["school", "class"])

for name, group in grouped:
    print("Group:", name)
    print(group)
    print()

Group: ('s001', 'V')
  school class            name  age
0   s001     V  Alberto Franco   12

Group: ('s001', 'VI')
  school class          name  age
3   s001    VI  Eesha Hinton   13

Group: ('s002', 'V')
  school class          name  age
1   s002     V  Gino Mcneill   12
4   s002     V  Gino Mcneill   14

Group: ('s003', 'VI')
  school class         name  age
2   s003    VI  Ryan Parkes   13

Group: ('s004', 'VI')
  school class          name  age
5   s004    VI  David Parkes   12

In [12]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ]
}

df = pd.DataFrame(data)

grouped = df.groupby("school")

groups = list(grouped)

print(groups)

[('s001',   school            name
0   s001  Alberto Franco
3   s001    Eesha Hinton), ('s002',   school          name
1   s002  Gino Mcneill
4   s002  Gino Mcneill), ('s003',   school         name
2   s003  Ryan Parkes), ('s004',   school          name
5   s004  David Parkes)]