<a href="https://colab.research.google.com/github/sejal-oli7/python/blob/main/python%20/%20%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas Exercise 1
We need pandas to get to know about the pandas.

In [3]:
#@ Importing necessary
import pandas as pd
import numpy as np

In [4]:
import pandas as pd

df = pd.read_csv("food.tsv", sep="\t")

print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'food.tsv'

## Pandas EXercise 2

In [21]:
#@ IMporting Library
import pandas as pd
import numpy as np

In [22]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"

df = pd.read_csv(
    url,
    sep="|",
    index_col="user_id"
)

print(df.head())

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [23]:
df.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [24]:
df.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [25]:
#@ how many numbers of data we have?
df.shape [0]

943

In [26]:
df.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [27]:
df.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [28]:
#@ only print occupation columns
df.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [29]:
df['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [31]:
#@ how many different occupations are in the datasets
df.occupation.nunique()

21

In [32]:
df.occupation.value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [33]:
df.occupation.value_counts().count()

np.int64(21)

In [34]:
#@ Lets describe your dataset by summarizing it
df.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

Only numeric columns are return , if you only describe the dataframe

In [35]:
#@ If we need all then
df.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [36]:
df.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [37]:
#@ what is the mean age of users?
round(df.age.mean())

34

In [38]:
#@ the least occurance of age
df.age.value_counts().tail()

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64

## Pandas Exercise3

In [39]:
import pandas as pd

In [40]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url, sep='\t')

In [41]:
#@ inspecting the dataset
df.head(20)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75

In [42]:
#@ number of observation
df.shape[0]

4622

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [44]:
df.shape[1]

5

In [45]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [46]:
#@ which was the most order items
#group by
i = df.groupby('item_name')
i
i= i.sum()
i = i.sort_values(['quantity'], ascending=False)
i.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

In [47]:
#@ what was the most order item in the choice description column
df.groupby('choice_description').sum().sort_values(['quantity'], ascending=False).head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,$2.18 $1.09 $1.09 $6.49 $2.18 $1.25 $1.09 $6.4...

In [48]:
import pandas as pd
data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ],
    "date_Of_Birth": [
        "15/05/2002",
        "17/05/2002",
        "16/02/1999",
        "25/09/1998",
        "11/05/2002",
        "15/09/1997"
    ],
    "age": [12, 12, 13, 13, 14, 12],
    "height": [173, 192, 186, 167, 151, None],
    "weight": [35, 32, 33, 30, 31, None],
    "address": [
        "street1",
        "street2",
        "street3",
        "street1",
        "street2",
        None
    ]
}

df = pd.DataFrame(data)

# Group by school
grouped = df.groupby("school")

# Check the type
print(type(grouped))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [49]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "age": [12, 12, 13, 13, 14, 12]
}

df = pd.DataFrame(data)

result = df.groupby("school")["age"].agg(
    ["mean", "min", "max"]
)

print(result)

        mean  min  max
school
s001    12.5   12   13
s002    13.0   12   14
s003    13.0   13   13
s004    12.0   12   12

In [50]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ],
    "age": [12, 12, 13, 13, 14, 12]
}

df = pd.DataFrame(data)

grouped = df.groupby(["school", "class"])

for name, group in grouped:
    print("Group:", name)
    print(group)
    print()

Group: ('s001', 'V')
  school class            name  age
0   s001     V  Alberto Franco   12

Group: ('s001', 'VI')
  school class          name  age
3   s001    VI  Eesha Hinton   13

Group: ('s002', 'V')
  school class          name  age
1   s002     V  Gino Mcneill   12
4   s002     V  Gino Mcneill   14

Group: ('s003', 'VI')
  school class         name  age
2   s003    VI  Ryan Parkes   13

Group: ('s004', 'VI')
  school class          name  age
5   s004    VI  David Parkes   12

In [51]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ]
}

df = pd.DataFrame(data)

grouped = df.groupby("school")

groups = list(grouped)

print(groups)

[('s001',   school            name
0   s001  Alberto Franco
3   s001    Eesha Hinton), ('s002',   school          name
1   s002  Gino Mcneill
4   s002  Gino Mcneill), ('s003',   school         name
2   s003  Ryan Parkes), ('s004',   school          name
5   s004  David Parkes)]

In [52]:
import pandas as pd

data = {
    "school": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"]
}

df = pd.DataFrame(data)

result = df.groupby("school").size()

print(result)

school
s001    2
s002    2
s003    1
s004    1
dtype: int64